apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: spring-test
spec:
  selector:
    app: spring-test-app
  ports:
    - protocol: TCP
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer
  loadBalancerIP: "35.223.39.248"
  
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-test-app
spec:
  selector:
    matchLabels:
      app: spring-test-app
  replicas: 2 # Number of replicas that will be created for this deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-test-app
    spec:
      containers:
        - name: spring-test-app 
          image: 13309661021/a3-springboot:v16
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster